/**
 * Generates `src/pages/Admin/utils/sltLogoImage.js` from `src/assets/slt-logo.png`.
 *
 * PDF image XObjects cannot read PNG containers, so the PNG is decoded here at
 * build time, flattened onto a white background (the report header is white),
 * re-deflated, and emitted as hex ready for an ASCIIHexDecode stream.
 *
 * Run with: node scripts/buildSltLogoPdfImage.js
 */
const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const ROOT = path.resolve(__dirname, '..');
const SRC_PNG = path.join(ROOT, 'src', 'assets', 'slt-logo.png');
const OUT_JS = path.join(ROOT, 'src', 'pages', 'Admin', 'utils', 'sltLogoImage.js');

function readChunks(buf) {
  const chunks = [];
  let i = 8;
  while (i + 8 <= buf.length) {
    const length = buf.readUInt32BE(i);
    const type = buf.slice(i + 4, i + 8).toString('ascii');
    const data = buf.slice(i + 8, i + 8 + length);
    chunks.push({ type, data });
    i += 12 + length;
  }
  return chunks;
}

function paeth(a, b, c) {
  const p = a + b - c;
  const pa = Math.abs(p - a);
  const pb = Math.abs(p - b);
  const pc = Math.abs(p - c);
  if (pa <= pb && pa <= pc) return a;
  if (pb <= pc) return b;
  return c;
}

function unfilter(raw, width, height, bpp) {
  const stride = width * bpp;
  const out = Buffer.alloc(stride * height);
  let pos = 0;
  for (let y = 0; y < height; y++) {
    const filter = raw[pos++];
    const line = raw.slice(pos, pos + stride);
    pos += stride;
    const cur = out.slice(y * stride, (y + 1) * stride);
    const prev = y > 0 ? out.slice((y - 1) * stride, y * stride) : null;
    for (let x = 0; x < stride; x++) {
      const a = x >= bpp ? cur[x - bpp] : 0;
      const b = prev ? prev[x] : 0;
      const c = prev && x >= bpp ? prev[x - bpp] : 0;
      let value = line[x];
      switch (filter) {
        case 0: break;
        case 1: value += a; break;
        case 2: value += b; break;
        case 3: value += (a + b) >> 1; break;
        case 4: value += paeth(a, b, c); break;
        default: throw new Error(`Unsupported PNG filter ${filter} on row ${y}`);
      }
      cur[x] = value & 0xff;
    }
  }
  return out;
}

function main() {
  const png = fs.readFileSync(SRC_PNG);
  const chunks = readChunks(png);
  const ihdr = chunks.find((c) => c.type === 'IHDR');
  if (!ihdr) throw new Error('PNG is missing its IHDR chunk');

  const width = ihdr.data.readUInt32BE(0);
  const height = ihdr.data.readUInt32BE(4);
  const bitDepth = ihdr.data[8];
  const colorType = ihdr.data[9];
  const interlace = ihdr.data[12];

  if (bitDepth !== 8) throw new Error(`Unsupported PNG bit depth ${bitDepth}`);
  if (interlace !== 0) throw new Error('Interlaced PNGs are not supported');

  const channels = { 0: 1, 2: 3, 4: 2, 6: 4 }[colorType];
  if (!channels) throw new Error(`Unsupported PNG color type ${colorType}`);

  const idat = Buffer.concat(chunks.filter((c) => c.type === 'IDAT').map((c) => c.data));
  const pixels = unfilter(zlib.inflateSync(idat), width, height, channels);

  // Flatten onto white so the transparent background does not turn black.
  const rgb = Buffer.alloc(width * height * 3);
  for (let i = 0; i < width * height; i++) {
    const s = i * channels;
    let r = pixels[s];
    let g = channels >= 3 ? pixels[s + 1] : pixels[s];
    let b = channels >= 3 ? pixels[s + 2] : pixels[s];
    if (channels === 4 || channels === 2) {
      const alpha = channels === 4 ? pixels[s + 3] : pixels[s + 1];
      const a = alpha / 255;
      r = Math.round(r * a + 255 * (1 - a));
      g = Math.round(g * a + 255 * (1 - a));
      b = Math.round(b * a + 255 * (1 - a));
    }
    rgb[i * 3] = r;
    rgb[i * 3 + 1] = g;
    rgb[i * 3 + 2] = b;
  }

  const deflated = zlib.deflateSync(rgb, { level: 9 });
  const hex = deflated.toString('hex');

  const contents = `// AUTO-GENERATED by scripts/buildSltLogoPdfImage.js - do not edit by hand.
// Source: src/assets/slt-logo.png (${width}x${height}, PNG color type ${colorType})
export const SLT_LOGO_WIDTH = ${width};
export const SLT_LOGO_HEIGHT = ${height};
export const SLT_LOGO_HEX = '${hex}';
`;

  fs.writeFileSync(OUT_JS, contents);
  console.log(`Wrote ${path.relative(ROOT, OUT_JS)} (${width}x${height}, ${deflated.length} bytes compressed)`);
}

main();